# Form implementation generated from reading ui file 'PicFusion.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 335)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 335))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.imageListWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.imageListWidget.setDragEnabled(True)
        self.imageListWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.DragDrop)
        self.imageListWidget.setDefaultDropAction(QtCore.Qt.DropAction.MoveAction)
        self.imageListWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.imageListWidget.setObjectName("imageListWidget")
        self.verticalLayout.addWidget(self.imageListWidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.mergeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mergeButton.setObjectName("mergeButton")
        self.gridLayout.addWidget(self.mergeButton, 2, 0, 1, 1)
        self.ResizecheckBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.ResizecheckBox.setObjectName("ResizecheckBox")
        self.gridLayout.addWidget(self.ResizecheckBox, 1, 2, 1, 1)
        self.addButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 0, 0, 1, 1)
        self.removeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.removeButton.setObjectName("removeButton")
        self.gridLayout.addWidget(self.removeButton, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PicFusion"))
        self.label.setText(_translate("MainWindow", "Drag and drop to reorder images:"))
        self.mergeButton.setText(_translate("MainWindow", "Merge Images"))
        self.ResizecheckBox.setText(_translate("MainWindow", "Resize"))
        self.addButton.setText(_translate("MainWindow", "Add Images"))
        self.removeButton.setText(_translate("MainWindow", "Remove Selected"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Vertical"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Horizontal"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Grid"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
